### ISSUE TITLE
出錯誤了。。。。。

### ISSUE THREAD

**Issue by ssrv2ray** [papagaye744/iptv-go#10]
布署後 打開 鏈接 顯示“链接错误!” https://live-go.vercel.app/
 https://live-test.vercel.app/
請修正這個問題！！

**Comment by papagaye744** [comment]
你链接缺少了参数，这个要用要加上平台和房间号或者用一起看
你可以参考这个[https://github.com/youshandefeiyang/LiveRedirect/blob/main/Golang/README.md](https://github.com/youshandefeiyang/LiveRedirect/blob/main/Golang/README.md)
例如：[https://live-go.vercel.app/huya/660000](https://live-go.vercel.app/huya/660000)
