### ISSUE TITLE
无法部署

### ISSUE THREAD

**Issue by v6wind** [papagaye744/iptv-go#22]
之前一直在用，今天看见更新了，于是重新部署。

Error: The following Serverless Functions contain an invalid "runtime":
  - api/index (provided.al2)
  - api/live (provided.al2)
  - api/yqk/yqk (provided.al2). Learn More: https://vercel.com/guides/serverless-function-contains-invalid-runtime-error

**Comment by v6wind** [comment]
问题解决了，去settings那里，设置一下Node.js Version版本18.x就可以了。不知道为什么，添加package.json，指定"node": "18"却没有生效。。

**Comment by v6wind** [comment]
问题解决了，去settings设置一下Node.js Version为18.x就可以了，不过明明看见package.json已经设置了"node": "18.x"，部署的时候却没有生效。

**Comment by papagaye744** [comment]
> 问题解决了，去settings设置一下Node.js Version为18.x就可以了，不过明明看见package.json已经设置了"node": "18.x"，部署的时候却没有生效。

是吗？我就是看了文档可以指定版本才加上的，然后我自己现在setting选了20.x是可以的
