### ISSUE TITLE
这个部署完了，是怎么使用啊？

### ISSUE THREAD

**Issue by zhuweijia** [papagaye744/iptv-go#27]
部署完，有个域名https://iptv-go-live.vercel.app/，是直接使用这个域名跟上 /huya/xxx  或者 /douyu/xxx吗？ 

https://iptv-go-live.vercel.app/huya/xxx 
https://iptv-go-live.vercel.app/douyu/xxx 

我看肥羊的仓库教程写的是使用docker，但是这个部署完了，不知道怎么和docker那些联系到一起。
我是初学者，比较小白，可能问的比较低级，麻烦大佬帮忙解答下。感谢

还有一个问题想问下，这个部署的服务，是一直在线的吗？需要每次 保活 吗？

**Comment by zhuweijia** [comment]
> 是的，和肥羊一样就是 `http://你的IP:35455` 这部分换成你自己部署后的域名
> 
> 一直在线的 不用保活

我发现一个问题，现在 vercel 是不是 被墙了，通过这个得到的域名，必须挂代理才能访问。

**Comment by papagaye744** [comment]
> > 是的，和肥羊一样就是 `http://你的IP:35455` 这部分换成你自己部署后的域名
> > 一直在线的 不用保活
> 
> 我发现一个问题，现在 vercel 是不是 被墙了，通过这个得到的域名，必须挂代理才能访问。 @papagaye744

是的 不想挂代理需要自定义域名
